server:
  port: 8001
spring:
  application:
    name: gateway-demo
eureka:
  client:
    service-url:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka


zuul:
  prefix: /naolu
  routes:
    #路由配置
    template:
      path: /clientB/**
      serviceId: CLIENTB
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000

