server:
  port: 9001
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false  #表示是否注册自身到eureka服务器
    fetch-registry: false #是否从eureka上获取注册信息
    service-url:
      defaultZone:  http://server2:9002/eureka/
